import { Lens } from "@shared/schema";

// Todas as 43 lentes da planilha PRECIFICAÇÃO_REAL simplificada
export const defaultLensData: Lens[] = [
  {
    "id": 1,
    "nome": "LT CR-39",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -6,00 a +4,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.56",
    "precoVista": "R$ 399,00",
    "parcela3x": "R$ 159,60",
    "parcela6x": "R$ 89,77",
    "parcela10x": "R$ 65,84"
  },
  {
    "id": 2,
    "nome": "LT CR-39",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -6,00 a +6,00 / Cil. -2,25 a -4,00",
    "esf": null,
    "cil": null,
    "espessura": "1.56",
    "precoVista": "R$ 499,00",
    "parcela3x": "R$ 199,60",
    "parcela6x": "R$ 112,27",
    "parcela10x": "R$ 82,34"
  },
  {
    "id": 3,
    "nome": "LT CR-39",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -4,00 a +4,00 / Cil. -4,25 a -6,00",
    "esf": null,
    "cil": null,
    "espessura": "1.56",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 4,
    "nome": "LT CR-39",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "medidas": "Esf. -4,00 a +4,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.56",
    "precoVista": "R$ 499,00",
    "parcela3x": "R$ 199,60",
    "parcela6x": "R$ 112,27",
    "parcela10x": "R$ 82,34"
  },
  {
    "id": 5,
    "nome": "LT CR-39",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "medidas": "Esf. -4,00 a +4,00 / Cil. -2,25 a -4,00",
    "esf": null,
    "cil": null,
    "espessura": "1.56",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 6,
    "nome": "LT CR-39",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": true,
    "medidas": "Esf. -6,00 a +4,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.56",
    "precoVista": "R$ 499,00",
    "parcela3x": "R$ 199,60",
    "parcela6x": "R$ 112,27",
    "parcela10x": "R$ 82,34"
  },
  {
    "id": 7,
    "nome": "LT CR-39 ",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": true,
    "medidas": "Esf. -4,00 a +4,00 / Cil. -2,25 a -4,00",
    "esf": null,
    "cil": null,
    "espessura": "1.56",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 8,
    "nome": "LT CR-39",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": true,
    "medidas": "Esf. -4,00 a +2,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.56",
    "precoVista": "R$ 699,00",
    "parcela3x": "R$ 279,60",
    "parcela6x": "R$ 157,28",
    "parcela10x": "R$ 115,33"
  },
  {
    "id": 9,
    "nome": "LT CR-39",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": true,
    "medidas": "Esf. -4,00 a +2,00 / Cil. -2,25 a -4,00",
    "esf": null,
    "cil": null,
    "espessura": "1.56",
    "precoVista": "R$ 799,00",
    "parcela3x": "R$ 319,60",
    "parcela6x": "R$ 179,78",
    "parcela10x": "R$ 131,83"
  },
  {
    "id": 10,
    "nome": "LT POLI ",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -4,00 a +4,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.59",
    "precoVista": "R$ 499,00",
    "parcela3x": "R$ 199,60",
    "parcela6x": "R$ 112,27",
    "parcela10x": "R$ 82,34"
  },
  {
    "id": 11,
    "nome": "LT POLI",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -5,00 a +4,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.59",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 12,
    "nome": "LT POLI",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -2,00 a +3,00 / Cil. -2,25 a -4,00",
    "esf": null,
    "cil": null,
    "espessura": "1.59",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 13,
    "nome": "LT POLI HAYTEK",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "medidas": "Esf. -4,00 a +2,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.59",
    "precoVista": "R$ 799,00",
    "parcela3x": "R$ 319,60",
    "parcela6x": "R$ 179,78",
    "parcela10x": "R$ 131,83"
  },
  {
    "id": 14,
    "nome": "LT POLI HAYTEK",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "medidas": "Esf. -4,00 a +2,00 / Cil. -2,25 a -4,00",
    "esf": null,
    "cil": null,
    "espessura": "1.59",
    "precoVista": "R$ 899,00",
    "parcela3x": "R$ 359,60",
    "parcela6x": "R$ 202,28",
    "parcela10x": "R$ 148,33"
  },
  {
    "id": 15,
    "nome": "LT POLI",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": true,
    "medidas": "Esf. -6,00 a +4,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.59",
    "precoVista": "R$ 899,00",
    "parcela3x": "R$ 359,60",
    "parcela6x": "R$ 202,28",
    "parcela10x": "R$ 148,33"
  },
  {
    "id": 16,
    "nome": "LT POLI ",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": true,
    "medidas": "Esf. -6,00 a +4,00 / Cil. -2,25 a -4,00",
    "esf": null,
    "cil": null,
    "espessura": "1.59",
    "precoVista": "R$ 999,00",
    "parcela3x": "R$ 399,60",
    "parcela6x": "R$ 224,78",
    "parcela10x": "R$ 164,83"
  },
  {
    "id": 17,
    "nome": "LT TRANSITIONS",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -2,00 a +2,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.50",
    "precoVista": "R$ 899,00",
    "parcela3x": "R$ 359,60",
    "parcela6x": "R$ 202,28",
    "parcela10x": "R$ 148,33"
  },
  {
    "id": 18,
    "nome": "LT ALTO INDICE ~ SHINEDUX",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": true,
    "medidas": "Esf. -10,00 a +7,00 / Esf. -6,00 a +6,00 / Cil. -4,00 Esf. -6,25 a -10,00 / Cil. -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.61",
    "precoVista": "R$ 999,00",
    "parcela3x": "R$ 399,60",
    "parcela6x": "R$ 224,78",
    "parcela10x": "R$ 164,83"
  },
  {
    "id": 19,
    "nome": "LT ALTO INDICE - SHINEDUX",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -10,00 a +7,00 / Esf. -6,00 a +6,00 / Cil. -4,00 Esf. -6,25 a -10,00 / Cil. -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.61",
    "precoVista": "R$ 899,00",
    "parcela3x": "R$ 359,60",
    "parcela6x": "R$ 202,28",
    "parcela10x": "R$ 148,33"
  },
  {
    "id": 20,
    "nome": "LT ALTO INDICE - SHINEDUX",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -3,00 a -15,00 / Esf. -3,00 a -10,00 / Cil. -4,00 Esf. -10,25 a -12,00 / Cil. -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.67",
    "precoVista": "R$ 1199,00",
    "parcela3x": "R$ 479,60",
    "parcela6x": "R$ 269,78",
    "parcela10x": "R$ 197,83"
  },
  {
    "id": 21,
    "nome": "LT ALTO INDICE - SHINEDUX",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": true,
    "medidas": "Esf. -3,00 a -15,00 / Esf. -3,00 a -10,00 / Cil. -4,00 Esf. -10,25 a -12,00 / Cil. -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.67",
    "precoVista": "R$ 1399,00",
    "parcela3x": "R$ 559,60",
    "parcela6x": "R$ 314,78",
    "parcela10x": "R$ 230,83"
  },
  {
    "id": 22,
    "nome": "LT ALTO INDICE ",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "medidas": "Esf. -10,00 a +6,00 / Esf. -8,00 a +6,00 / Cil. -4,00 Esf. -8,25 a -10,00 / Cil. -3,00",
    "esf": null,
    "cil": null,
    "espessura": "1.67",
    "precoVista": "R$ 1299,00",
    "parcela3x": "R$ 519,60",
    "parcela6x": "R$ 292,28",
    "parcela10x": "R$ 214,33"
  },
  {
    "id": 23,
    "nome": "LT ALTO INDICE  RESIDUAL VERDE ",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": true,
    "medidas": "Esf. -10,00 a +6,00 / Cil. -0,25 a -4,00",
    "esf": null,
    "cil": null,
    "espessura": "1.67",
    "precoVista": "R$ 1299,00",
    "parcela3x": "R$ 519,60",
    "parcela6x": "R$ 292,28",
    "parcela10x": "R$ 214,33"
  },
  {
    "id": 24,
    "nome": "LT ALTO INDICE  RESIDUAL VERDE ",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": true,
    "medidas": "Esf. -1,00 a -15,00 / Cil. -0,25 a -3,00",
    "esf": null,
    "cil": null,
    "espessura": "1.74",
    "precoVista": "R$ 1899,00",
    "parcela3x": "R$ 759,60",
    "parcela6x": "R$ 427,28",
    "parcela10x": "R$ 313,34"
  },
  {
    "id": 25,
    "nome": "LT ULTRAX TRIVEX  -  HOYA",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -4,00 a +3,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.53",
    "precoVista": "R$ 999,00",
    "parcela3x": "R$ 399,60",
    "parcela6x": "R$ 224,78",
    "parcela10x": "R$ 164,83"
  },
  {
    "id": 26,
    "nome": "LT ULTRAX TRIVEX TRANSITIONS  -  HOYA",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "Esf. -4,00 a +3,00 / Cil. -0,25 a -2,00",
    "esf": null,
    "cil": null,
    "espessura": "1.53",
    "precoVista": "R$ 1299,00",
    "parcela3x": "R$ 519,60",
    "parcela6x": "R$ 292,28",
    "parcela10x": "R$ 214,33"
  },
  {
    "id": 27,
    "nome": "LT CR-39 - MARRON / CINZA / BLACK / G-15",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "CURVA 600",
    "esf": null,
    "cil": null,
    "espessura": " 70mm",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 28,
    "nome": "LT CR-39 ~ DEGRADE - MARRON / CINZA / BLACK / G-15",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "CURVA 600",
    "esf": null,
    "cil": null,
    "espessura": "70mm",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 29,
    "nome": "LT CR-39 - CINZA / MARRON /G-15",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "CURVA 800",
    "esf": null,
    "cil": null,
    "espessura": "70mm",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 30,
    "nome": "LT POLARIZADA - CINZA / MARRON / G-15",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "CURVA 600",
    "esf": null,
    "cil": null,
    "espessura": "70mm",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 31,
    "nome": "LT ESPELHADA  -  AZUL / VERMELHA / PRATA / GOLD",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "CURVA 600",
    "esf": null,
    "cil": null,
    "espessura": "70mm",
    "precoVista": "R$ 399,00",
    "parcela3x": "R$ 159,60",
    "parcela6x": "R$ 89,77",
    "parcela10x": "R$ 65,84"
  },
  {
    "id": 32,
    "nome": "LT POLI - MARRON / CINZA /G-15",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "CURVA 600 / 800",
    "esf": null,
    "cil": null,
    "espessura": "70mm",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 33,
    "nome": "LT POLI - DEGRADE / CINZA / MARRON",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "CURVA 600",
    "esf": null,
    "cil": null,
    "espessura": "70mm",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 34,
    "nome": "LT CRISTAL - G-15",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "CURVA 600",
    "esf": null,
    "cil": null,
    "espessura": "70mm",
    "precoVista": "R$ 299,00",
    "parcela3x": "R$ 119,60",
    "parcela6x": "R$ 67,27",
    "parcela10x": "R$ 49,34"
  },
  {
    "id": 35,
    "nome": "MONTAGEM CR39",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": null,
    "esf": null,
    "cil": null,
    "espessura": "",
    "precoVista": "R$ 99,00",
    "parcela3x": "R$ 39,60",
    "parcela6x": "R$ 22,28",
    "parcela10x": "R$ 16,34"
  },
  {
    "id": 36,
    "nome": "MONTAGEM POLI / ALTO INDICE",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": null,
    "esf": null,
    "cil": null,
    "espessura": "",
    "precoVista": "R$ 99,00",
    "parcela3x": "R$ 39,60",
    "parcela6x": "R$ 22,28",
    "parcela10x": "R$ 16,34"
  },
  {
    "id": 37,
    "nome": "MONTAGEM PARAFUSADO",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": null,
    "esf": null,
    "cil": null,
    "espessura": "",
    "precoVista": "R$ 99,00",
    "parcela3x": "R$ 39,60",
    "parcela6x": "R$ 22,28",
    "parcela10x": "R$ 16,34"
  },
  {
    "id": 38,
    "nome": "COLORACAO SUAVE / ESPORTE",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": null,
    "esf": null,
    "cil": null,
    "espessura": "",
    "precoVista": "R$ 99,00",
    "parcela3x": "R$ 39,60",
    "parcela6x": "R$ 22,28",
    "parcela10x": "R$ 16,34"
  },
  {
    "id": 39,
    "nome": "COLORACAO DEGRADE",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": null,
    "esf": null,
    "cil": null,
    "espessura": "",
    "precoVista": "R$ 99,00",
    "parcela3x": "R$ 39,60",
    "parcela6x": "R$ 22,28",
    "parcela10x": "R$ 16,34"
  },
  {
    "id": 40,
    "nome": "BF ULTEX / KRIPTOK  ACABADO",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "ESF. 0,00/3,00 - AD: 1,00 a 3,00",
    "esf": null,
    "cil": null,
    "espessura": "15mm",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 41,
    "nome": "MF CR-39 - SHINEDUX",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "ESF. 0,00/2,00  -  AD: 1,00 a 3,00",
    "esf": null,
    "cil": null,
    "espessura": "18mm",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 42,
    "nome": "MF CR-39 ~ FREE LINE / PRO LIFE",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "ESF. 0,00/2,00 - AD: 1,00 a 3,00",
    "esf": null,
    "cil": null,
    "espessura": "18mm",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 43,
    "nome": "MF CR-39",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "medidas": "ESF. 0,00/3,00  -  AD: 1,00 a 3,00",
    "esf": null,
    "cil": null,
    "espessura": "14mm",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 44,
    "nome": "MF CR-39 - SHINEDUX",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": true,
    "medidas": "ESF. 0,00/3,00  -  AD: 1,00 a 3,00",
    "esf": null,
    "cil": null,
    "espessura": "14mm",
    "precoVista": "R$ 699,00",
    "parcela3x": "R$ 279,60",
    "parcela6x": "R$ 157,28",
    "parcela10x": "R$ 115,33"
  },
  {
    "id": 45,
    "nome": "MF CR-39",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": true,
    "blueCut": false,
    "medidas": "ESF. 0,00/3,00  -  AD: 1,00 a 3,00",
    "esf": null,
    "cil": null,
    "espessura": "14mm",
    "precoVista": "R$ 599,00",
    "parcela3x": "R$ 239,60",
    "parcela6x": "R$ 134,78",
    "parcela10x": "R$ 98,84"
  },
  {
    "id": 46,
    "nome": "MF CR-39  -  SHINEDUX",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "medidas": "ESF. 0,00/3,00  -  AD: 1,00 a 3,00",
    "esf": null,
    "cil": null,
    "espessura": "14mm",
    "precoVista": "R$ 699,00",
    "parcela3x": "R$ 279,60",
    "parcela6x": "R$ 157,28",
    "parcela10x": "R$ 115,33"
  },
  {
    "id": 47,
    "nome": "MF CR39 - AUDAX",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "medidas": "ESF. 0,00/3,00  -  AD: 1,00 a 3,00",
    "esf": null,
    "cil": null,
    "espessura": "14mm",
    "precoVista": "R$ 899,00",
    "parcela3x": "R$ 359,60",
    "parcela6x": "R$ 202,28",
    "parcela10x": "R$ 148,33"
  },
  {
    "id": 48,
    "nome": "MF POLICARBONATO - SHINEDUX",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": true,
    "medidas": "ESF. 0,00/2,00 - AD: 1,00 a 3,00",
    "esf": null,
    "cil": null,
    "espessura": "14mm",
    "precoVista": "R$ 1199,00",
    "parcela3x": "R$ 479,60",
    "parcela6x": "R$ 269,78",
    "parcela10x": "R$ 197,83"
  }
];

export const questions = [
  {
    text: "É incolor?",
    key: "incolor" as const,
    options: [
      { label: "Sim", value: true },
      { label: "Não", value: false }
    ]
  },
  {
    text: "Tem antirreflexo?",
    key: "antireflexo" as const,
    options: [
      { label: "Sim", value: true },
      { label: "Não", value: false }
    ]
  },
  {
    text: "É fotosensível?",
    key: "fotosensivel" as const,
    options: [
      { label: "Sim", value: true },
      { label: "Não", value: false }
    ]
  },
  {
    text: "Tem blue cut?",
    key: "blueCut" as const,
    options: [
      { label: "Sim", value: true },
      { label: "Não", value: false }
    ]
  },
  {
    text: "Qual a faixa de grau?",
    key: "medidas" as const,
    options: [
      { label: "-1.00 a +1.00", value: "-1.00 a +1.00" },
      { label: "-2.00 a +2.00", value: "-2.00 a +2.00" },
      { label: "-4.00 a +4.00", value: "-4.00 a +4.00" },
      { label: "-6.00 a +6.00", value: "-6.00 a +6.00" }
    ]
  },
  {
    text: "Qual a espessura?",
    key: "espessura" as const,
    options: [
      { label: "1.50", value: "1.50" },
      { label: "1.67", value: "1.67" },
      { label: "1.74", value: "1.74" }
    ]
  }
];

export const getQuestionLabel = (key: string): string => {
  const labels: Record<string, string> = {
    'incolor': 'É INCOLOR',
    'antireflexo': 'TEM ANTIREFLEXO',
    'fotosensivel': 'É FOTOSENSÍVEL',
    'blueCut': 'TEM BLUE CUT',
    'medidas': 'EM QUAL FAIXA ESTÁ O GRAU',
    'espessura': 'QUAL A ESPESSURA'
  };
  return labels[key] || key;
};
