import { Lens } from "@shared/schema";

// Todas as 43 lentes da planilha PRECIFICAÇÃO_REAL com tipo de visão  
export const defaultLensData: any[] = [
  {
    "id": 1,
    "nome": "LT CR-39 - MARRON / CINZA / BLACK / G-15",
    "tipo": "LENTES SOLARES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "CURVA 600",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 2,
    "nome": "LT CR-39 ~ DEGRADE - MARRON / CINZA / BLACK / G-15",
    "tipo": "LENTES SOLARES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "CURVA 600",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 3,
    "nome": "LT CR-39 - CINZA / MARRON /G-15",
    "tipo": "LENTES SOLARES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "CURVA 800",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 4,
    "nome": "LT POLARIZADA - CINZA / MARRON / G-15",
    "tipo": "LENTES SOLARES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "CURVA 600",
    "precoVista": "R$ 239,00",
    "parcela3x": "R$ 95,60",
    "parcela6x": "R$ 53,73",
    "parcela10x": "R$ 39,41"
  },
  {
    "id": 5,
    "nome": "LT POLARIZADA ~ DEGRADE - CINZA / MARRON / G-15",
    "tipo": "LENTES SOLARES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "CURVA 600",
    "precoVista": "R$ 239,00",
    "parcela3x": "R$ 95,60",
    "parcela6x": "R$ 53,73",
    "parcela10x": "R$ 39,41"
  },
  {
    "id": 6,
    "nome": "LT ESPELHADA - PRATA / DOURADA / AZUL / ROSA / LARANJA",
    "tipo": "LENTES SOLARES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "CURVA 600",
    "precoVista": "R$ 219,00",
    "parcela3x": "R$ 87,60",
    "parcela6x": "R$ 49,23",
    "parcela10x": "R$ 36,13"
  },
  {
    "id": 7,
    "nome": "LT ESPELHADA - PRATA / DOURADA / AZUL / ROSA / LARANJA",
    "tipo": "LENTES SOLARES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "CURVA 800",
    "precoVista": "R$ 219,00",
    "parcela3x": "R$ 87,60",
    "parcela6x": "R$ 49,23",
    "parcela10x": "R$ 36,13"
  },
  {
    "id": 8,
    "nome": "LT ESPELHADA ~ DEGRADE - PRATA / DOURADA / AZUL / ROSA / LARANJA",
    "tipo": "LENTES SOLARES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "CURVA 600",
    "precoVista": "R$ 219,00",
    "parcela3x": "R$ 87,60",
    "parcela6x": "R$ 49,23",
    "parcela10x": "R$ 36,13"
  },
  {
    "id": 9,
    "nome": "CR-39 INCOLOR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "ESF. -6,00 À +4,00 / CIL. ATÉ -2,00",
    "precoVista": "R$ 89,00",
    "parcela3x": "R$ 35,60",
    "parcela6x": "R$ 20,00",
    "parcela10x": "R$ 14,68"
  },
  {
    "id": 10,
    "nome": "CR-39 AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "ESF. -6,00 À +4,00 / CIL. ATÉ -2,00",
    "precoVista": "R$ 129,00",
    "parcela3x": "R$ 51,60",
    "parcela6x": "R$ 28,98",
    "parcela10x": "R$ 21,27"
  },
  {
    "id": 11,
    "nome": "CR-39 FOTOSSENSIVEL",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": true,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "ESF. -6,00 À +4,00 / CIL. ATÉ -2,00",
    "precoVista": "R$ 179,00",
    "parcela3x": "R$ 71,60",
    "parcela6x": "R$ 40,23",
    "parcela10x": "R$ 29,53"
  },
  {
    "id": 12,
    "nome": "CR-39 FOTOSSENSÍVEL + AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "ESF. -6,00 À +4,00 / CIL. ATÉ -2,00",
    "precoVista": "R$ 219,00",
    "parcela3x": "R$ 87,60",
    "parcela6x": "R$ 49,23",
    "parcela10x": "R$ 36,13"
  },
  {
    "id": 13,
    "nome": "CR-39 BLUE CUT",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": true,
    "espessura": "70mm",
    "medidas": "ESF. -6,00 À +4,00 / CIL. ATÉ -2,00",
    "precoVista": "R$ 139,00",
    "parcela3x": "R$ 55,60",
    "parcela6x": "R$ 31,23",
    "parcela10x": "R$ 22,92"
  },
  {
    "id": 14,
    "nome": "CR-39 BLUE CUT + AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": true,
    "espessura": "70mm",
    "medidas": "ESF. -6,00 À +4,00 / CIL. ATÉ -2,00",
    "precoVista": "R$ 179,00",
    "parcela3x": "R$ 71,60",
    "parcela6x": "R$ 40,23",
    "parcela10x": "R$ 29,53"
  },
  {
    "id": 15,
    "nome": "1.56 INCOLOR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "56mm",
    "medidas": "ESF. -8,00 À +6,00 / CIL. ATÉ -4,00",
    "precoVista": "R$ 149,00",
    "parcela3x": "R$ 59,60",
    "parcela6x": "R$ 33,48",
    "parcela10x": "R$ 24,57"
  },
  {
    "id": 16,
    "nome": "1.56 AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "56mm",
    "medidas": "ESF. -8,00 À +6,00 / CIL. ATÉ -4,00",
    "precoVista": "R$ 189,00",
    "parcela3x": "R$ 75,60",
    "parcela6x": "R$ 42,48",
    "parcela10x": "R$ 31,18"
  },
  {
    "id": 17,
    "nome": "1.56 FOTOSSENSÍVEL",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": true,
    "blueCut": false,
    "espessura": "56mm",
    "medidas": "ESF. -8,00 À +6,00 / CIL. ATÉ -4,00",
    "precoVista": "R$ 229,00",
    "parcela3x": "R$ 91,60",
    "parcela6x": "R$ 51,48",
    "parcela10x": "R$ 37,78"
  },
  {
    "id": 18,
    "nome": "1.56 FOTOSSENSÍVEL + AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "espessura": "56mm",
    "medidas": "ESF. -8,00 À +6,00 / CIL. ATÉ -4,00",
    "precoVista": "R$ 269,00",
    "parcela3x": "R$ 107,60",
    "parcela6x": "R$ 60,48",
    "parcela10x": "R$ 44,38"
  },
  {
    "id": 19,
    "nome": "1.56 BLUE CUT",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": true,
    "espessura": "56mm",
    "medidas": "ESF. -8,00 À +6,00 / CIL. ATÉ -4,00",
    "precoVista": "R$ 199,00",
    "parcela3x": "R$ 79,60",
    "parcela6x": "R$ 44,77",
    "parcela10x": "R$ 32,84"
  },
  {
    "id": 20,
    "nome": "1.56 BLUE CUT + AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": true,
    "espessura": "56mm",
    "medidas": "ESF. -8,00 À +6,00 / CIL. ATÉ -4,00",
    "precoVista": "R$ 239,00",
    "parcela3x": "R$ 95,60",
    "parcela6x": "R$ 53,73",
    "parcela10x": "R$ 39,41"
  },
  {
    "id": 21,
    "nome": "1.61 INCOLOR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "61mm",
    "medidas": "ESF. -10,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 219,00",
    "parcela3x": "R$ 87,60",
    "parcela6x": "R$ 49,23",
    "parcela10x": "R$ 36,13"
  },
  {
    "id": 22,
    "nome": "1.61 AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "61mm",
    "medidas": "ESF. -10,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 259,00",
    "parcela3x": "R$ 103,60",
    "parcela6x": "R$ 58,23",
    "parcela10x": "R$ 42,73"
  },
  {
    "id": 23,
    "nome": "1.61 FOTOSSENSÍVEL",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": true,
    "blueCut": false,
    "espessura": "61mm",
    "medidas": "ESF. -10,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 319,00",
    "parcela3x": "R$ 127,60",
    "parcela6x": "R$ 71,73",
    "parcela10x": "R$ 52,63"
  },
  {
    "id": 24,
    "nome": "1.61 FOTOSSENSÍVEL + AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "espessura": "61mm",
    "medidas": "ESF. -10,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 359,00",
    "parcela3x": "R$ 143,60",
    "parcela6x": "R$ 80,73",
    "parcela10x": "R$ 59,23"
  },
  {
    "id": 25,
    "nome": "1.61 BLUE CUT",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": true,
    "espessura": "61mm",
    "medidas": "ESF. -10,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 279,00",
    "parcela3x": "R$ 111,60",
    "parcela6x": "R$ 62,73",
    "parcela10x": "R$ 46,03"
  },
  {
    "id": 26,
    "nome": "1.61 BLUE CUT + AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": true,
    "espessura": "61mm",
    "medidas": "ESF. -10,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 319,00",
    "parcela3x": "R$ 127,60",
    "parcela6x": "R$ 71,73",
    "parcela10x": "R$ 52,63"
  },
  {
    "id": 27,
    "nome": "1.67 INCOLOR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "67mm",
    "medidas": "ESF. -12,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 299,00",
    "parcela3x": "R$ 119,60",
    "parcela6x": "R$ 67,23",
    "parcela10x": "R$ 49,33"
  },
  {
    "id": 28,
    "nome": "1.67 AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "67mm",
    "medidas": "ESF. -12,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 339,00",
    "parcela3x": "R$ 135,60",
    "parcela6x": "R$ 76,23",
    "parcela10x": "R$ 55,93"
  },
  {
    "id": 29,
    "nome": "1.67 FOTOSSENSÍVEL",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": true,
    "blueCut": false,
    "espessura": "67mm",
    "medidas": "ESF. -12,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 419,00",
    "parcela3x": "R$ 167,60",
    "parcela6x": "R$ 94,23",
    "parcela10x": "R$ 69,13"
  },
  {
    "id": 30,
    "nome": "1.67 FOTOSSENSÍVEL + AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": true,
    "blueCut": false,
    "espessura": "67mm",
    "medidas": "ESF. -12,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 459,00",
    "parcela3x": "R$ 183,60",
    "parcela6x": "R$ 103,23",
    "parcela10x": "R$ 75,73"
  },
  {
    "id": 31,
    "nome": "1.67 BLUE CUT",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": true,
    "espessura": "67mm",
    "medidas": "ESF. -12,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 379,00",
    "parcela3x": "R$ 151,60",
    "parcela6x": "R$ 85,23",
    "parcela10x": "R$ 62,53"
  },
  {
    "id": 32,
    "nome": "1.67 BLUE CUT + AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": false,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": true,
    "espessura": "67mm",
    "medidas": "ESF. -12,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 419,00",
    "parcela3x": "R$ 167,60",
    "parcela6x": "R$ 94,23",
    "parcela10x": "R$ 69,13"
  },
  {
    "id": 33,
    "nome": "1.74 INCOLOR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "74mm",
    "medidas": "ESF. -15,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 459,00",
    "parcela3x": "R$ 183,60",
    "parcela6x": "R$ 103,23",
    "parcela10x": "R$ 75,73"
  },
  {
    "id": 34,
    "nome": "1.74 AR",
    "tipo": "VISÃO SIMPLES",
    "incolor": true,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "74mm",
    "medidas": "ESF. -15,00 À +8,00 / CIL. ATÉ -6,00",
    "precoVista": "R$ 499,00",
    "parcela3x": "R$ 199,60",
    "parcela6x": "R$ 112,23",
    "parcela10x": "R$ 82,33"
  },
  {
    "id": 35,
    "nome": "BIFOCAL CR-39",
    "tipo": "BIFOCAIS CR-39",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "70mm",
    "medidas": "ESF. -6,00 À +4,00 / CIL. ATÉ -2,00 / ADIÇÃO ATÉ +3,00",
    "precoVista": "R$ 179,00",
    "parcela3x": "R$ 71,60",
    "parcela6x": "R$ 40,23",
    "parcela10x": "R$ 29,53"
  },
  {
    "id": 36,
    "nome": "MULTIFOCAL PROGRESSIVA 1.50 ACABADA",
    "tipo": "PROGRESSIVAS ACABADAS",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "50mm",
    "medidas": "ESF. -6,00 À +4,00 / CIL. ATÉ -2,00 / ADIÇÃO ATÉ +3,00",
    "precoVista": "R$ 299,00",
    "parcela3x": "R$ 119,60",
    "parcela6x": "R$ 67,23",
    "parcela10x": "R$ 49,33"
  },
  {
    "id": 37,
    "nome": "MULTIFOCAL PROGRESSIVA 1.50 ACABADA + AR",
    "tipo": "PROGRESSIVAS ACABADAS",
    "incolor": true,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "50mm",
    "medidas": "ESF. -6,00 À +4,00 / CIL. ATÉ -2,00 / ADIÇÃO ATÉ +3,00",
    "precoVista": "R$ 339,00",
    "parcela3x": "R$ 135,60",
    "parcela6x": "R$ 76,23",
    "parcela10x": "R$ 55,93"
  },
  {
    "id": 38,
    "nome": "MULTIFOCAL PROGRESSIVA 1.56 ACABADA",
    "tipo": "PROGRESSIVAS ACABADAS",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "56mm",
    "medidas": "ESF. -8,00 À +6,00 / CIL. ATÉ -4,00 / ADIÇÃO ATÉ +3,00",
    "precoVista": "R$ 399,00",
    "parcela3x": "R$ 159,60",
    "parcela6x": "R$ 89,73",
    "parcela10x": "R$ 65,83"
  },
  {
    "id": 39,
    "nome": "MULTIFOCAL PROGRESSIVA 1.56 ACABADA + AR",
    "tipo": "PROGRESSIVAS ACABADAS",
    "incolor": true,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "56mm",
    "medidas": "ESF. -8,00 À +6,00 / CIL. ATÉ -4,00 / ADIÇÃO ATÉ +3,00",
    "precoVista": "R$ 439,00",
    "parcela3x": "R$ 175,60",
    "parcela6x": "R$ 98,73",
    "parcela10x": "R$ 72,43"
  },
  {
    "id": 40,
    "nome": "MULTIFOCAL PROGRESSIVA 1.61 ACABADA",
    "tipo": "PROGRESSIVAS ACABADAS",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "61mm",
    "medidas": "ESF. -10,00 À +8,00 / CIL. ATÉ -6,00 / ADIÇÃO ATÉ +3,00",
    "precoVista": "R$ 519,00",
    "parcela3x": "R$ 207,60",
    "parcela6x": "R$ 116,73",
    "parcela10x": "R$ 85,63"
  },
  {
    "id": 41,
    "nome": "MULTIFOCAL PROGRESSIVA 1.61 ACABADA + AR",
    "tipo": "PROGRESSIVAS ACABADAS",
    "incolor": true,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "61mm",
    "medidas": "ESF. -10,00 À +8,00 / CIL. ATÉ -6,00 / ADIÇÃO ATÉ +3,00",
    "precoVista": "R$ 559,00",
    "parcela3x": "R$ 223,60",
    "parcela6x": "R$ 125,73",
    "parcela10x": "R$ 92,23"
  },
  {
    "id": 42,
    "nome": "MULTIFOCAL PROGRESSIVA 1.67 ACABADA",
    "tipo": "PROGRESSIVAS ACABADAS",
    "incolor": true,
    "antireflexo": false,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "67mm",
    "medidas": "ESF. -12,00 À +8,00 / CIL. ATÉ -6,00 / ADIÇÃO ATÉ +3,00",
    "precoVista": "R$ 659,00",
    "parcela3x": "R$ 263,60",
    "parcela6x": "R$ 148,23",
    "parcela10x": "R$ 108,83"
  },
  {
    "id": 43,
    "nome": "MULTIFOCAL PROGRESSIVA 1.67 ACABADA + AR",
    "tipo": "PROGRESSIVAS ACABADAS",
    "incolor": true,
    "antireflexo": true,
    "fotosensivel": false,
    "blueCut": false,
    "espessura": "67mm",
    "medidas": "ESF. -12,00 À +8,00 / CIL. ATÉ -6,00 / ADIÇÃO ATÉ +3,00",
    "precoVista": "R$ 699,00",
    "parcela3x": "R$ 279,60",
    "parcela6x": "R$ 157,23",
    "parcela10x": "R$ 115,43"
  }
];

export const questions = [
  {text: "Que tipo de visão?", key: "tipo", options: [
    {label: "VISÃO SIMPLES", value: "VISÃO SIMPLES"},
    {label: "LENTES SOLARES", value: "LENTES SOLARES"},
    {label: "BIFOCAIS", value: "BIFOCAIS CR-39"},
    {label: "PROGRESSIVAS", value: "PROGRESSIVAS ACABADAS"}
  ]},
  {text: "É incolor?", key: "incolor", options: [{label: "SIM", value: true}, {label: "NÃO", value: false}]},
  {text: "Tem antirreflexo?", key: "antireflexo", options: [{label: "SIM", value: true}, {label: "NÃO", value: false}]},
  {text: "É fotossensível?", key: "fotosensivel", options: [{label: "SIM", value: true}, {label: "NÃO", value: false}]},
  {text: "Tem blue cut?", key: "blueCut", options: [{label: "SIM", value: true}, {label: "NÃO", value: false}]}
];

export const getQuestionLabel = (key: string): string => {
  const labels: { [key: string]: string } = {
    incolor: "Incolor",
    antireflexo: "Antirreflexo", 
    fotosensivel: "Fotossensível",
    blueCut: "Blue Cut",
    tipo: "Tipo de Visão",
    medidas: "Medidas",
    espessura: "Espessura"
  };
  return labels[key] || key;
};